name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml  # 呼叫單元測試工作流程

  sonarqube:
    needs: unit-test  # 等待單元測試完成後才執行
    uses: ./.github/workflows/sonarqube.yml  # 呼叫 SonarQube 工作流程
